version: "3.9"
services:
  web:
    build: .
    depends_on:
      - voltdb
    environment:
      PORT: 8000
      HOST: 0.0.0.0
      DATASOURCE: "node1:21212"
    ports:
      - "8000:8000"
    networks:
      - voltLocalCluster
  voltdb:
    image: "voltdb/voltdb-community:latest"
    environment:
      HOST_COUNT: 1
      HOSTS: node1
    ports:
      - "8080:8080"
      - "21212:21212"
      - "21211:21211"
    container_name: node1
    networks:
      - voltLocalCluster

networks:
  voltLocalCluster:
    name: voltNetwork