version: "3.9"
services:
  web:
    build: .
    environment:
      PORT: "8000"
      DATASOURCE: "localhost:21212"
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app
  voltdb:
    image: "voltdb/voltdb-community:latest"
    environment:
      HOST_COUNT: 1
      HOSTS: node1
    ports:
      - "8080:8080"
      - "21212:21212"
      - "21211:21211"
    container_name: node1
    networks:
      - voltLocalCluster

networks:
  voltLocalCluster:
    name: voltNetwork