// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Flash
//
//  To send money between users
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /
//  Version: 0.0.1
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
