// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "To send money between users",
    "title": "Flash",
    "version": "0.0.1"
  },
  "paths": {
    "/": {
      "get": {
        "tags": [
          "home"
        ],
        "responses": {
          "200": {
            "description": "home page response",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    },
    "/api/v1/login": {
      "post": {
        "tags": [
          "users"
        ],
        "operationId": "login",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/loginRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "login user response",
            "schema": {
              "$ref": "#/definitions/loginResponse"
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/api/v1/rates/{base}/{target}": {
      "get": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "description": "View exchange rates",
        "tags": [
          "rates"
        ],
        "operationId": "GetRates",
        "parameters": [
          {
            "maxLength": 5,
            "minLength": 2,
            "type": "string",
            "name": "base",
            "in": "path",
            "required": true
          },
          {
            "maxLength": 5,
            "minLength": 2,
            "type": "string",
            "name": "target",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "type": "number"
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/api/v1/users/me/balance": {
      "get": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "description": "View balance",
        "tags": [
          "users"
        ],
        "operationId": "GetBalance",
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "type": "number"
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/api/v1/users/me/connections/{account_number}": {
      "post": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "description": "Connect to a registered bank",
        "tags": [
          "users"
        ],
        "operationId": "Connect",
        "parameters": [
          {
            "type": "string",
            "name": "account_number",
            "in": "path",
            "required": true
          },
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/connectRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/api/v1/users/me/transfers/{username_or_email}": {
      "post": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "description": "Send money to another user",
        "tags": [
          "users"
        ],
        "operationId": "Send",
        "parameters": [
          {
            "type": "string",
            "name": "username_or_email",
            "in": "path",
            "required": true
          },
          {
            "name": "amount",
            "in": "body",
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/api/v1/users/me/uploads/{account_number}": {
      "post": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "description": "Upload money from a connected bank",
        "tags": [
          "users"
        ],
        "operationId": "Upload",
        "parameters": [
          {
            "type": "string",
            "name": "account_number",
            "in": "path",
            "required": true
          },
          {
            "name": "amount",
            "in": "body",
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "connectRequest": {
      "type": "object",
      "required": [
        "bank_id",
        "branch_number",
        "holder_name"
      ],
      "properties": {
        "bank_id": {
          "type": "string"
        },
        "branch_number": {
          "type": "string"
        },
        "holder_name": {
          "type": "string"
        },
        "reference": {
          "type": "string"
        }
      }
    },
    "error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "loginRequest": {
      "type": "object",
      "required": [
        "username_or_email",
        "password"
      ],
      "properties": {
        "password": {
          "type": "string",
          "minLength": 1
        },
        "username_or_email": {
          "type": "string",
          "minLength": 1
        }
      }
    },
    "loginResponse": {
      "type": "object",
      "required": [
        "token",
        "expire_date"
      ],
      "properties": {
        "expire_date": {
          "type": "string",
          "format": "date-time"
        },
        "token": {
          "type": "string",
          "minLength": 1
        }
      }
    },
    "principle": {
      "type": "object",
      "required": [
        "id",
        "email",
        "username"
      ],
      "properties": {
        "email": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "username": {
          "type": "string"
        }
      }
    }
  },
  "securityDefinitions": {
    "Bearer": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "To send money between users",
    "title": "Flash",
    "version": "0.0.1"
  },
  "paths": {
    "/": {
      "get": {
        "tags": [
          "home"
        ],
        "responses": {
          "200": {
            "description": "home page response",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    },
    "/api/v1/login": {
      "post": {
        "tags": [
          "users"
        ],
        "operationId": "login",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/loginRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "login user response",
            "schema": {
              "$ref": "#/definitions/loginResponse"
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/api/v1/rates/{base}/{target}": {
      "get": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "description": "View exchange rates",
        "tags": [
          "rates"
        ],
        "operationId": "GetRates",
        "parameters": [
          {
            "maxLength": 5,
            "minLength": 2,
            "type": "string",
            "name": "base",
            "in": "path",
            "required": true
          },
          {
            "maxLength": 5,
            "minLength": 2,
            "type": "string",
            "name": "target",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "type": "number"
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/api/v1/users/me/balance": {
      "get": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "description": "View balance",
        "tags": [
          "users"
        ],
        "operationId": "GetBalance",
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "type": "number"
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/api/v1/users/me/connections/{account_number}": {
      "post": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "description": "Connect to a registered bank",
        "tags": [
          "users"
        ],
        "operationId": "Connect",
        "parameters": [
          {
            "type": "string",
            "name": "account_number",
            "in": "path",
            "required": true
          },
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/connectRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/api/v1/users/me/transfers/{username_or_email}": {
      "post": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "description": "Send money to another user",
        "tags": [
          "users"
        ],
        "operationId": "Send",
        "parameters": [
          {
            "type": "string",
            "name": "username_or_email",
            "in": "path",
            "required": true
          },
          {
            "name": "amount",
            "in": "body",
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/api/v1/users/me/uploads/{account_number}": {
      "post": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "description": "Upload money from a connected bank",
        "tags": [
          "users"
        ],
        "operationId": "Upload",
        "parameters": [
          {
            "type": "string",
            "name": "account_number",
            "in": "path",
            "required": true
          },
          {
            "name": "amount",
            "in": "body",
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "connectRequest": {
      "type": "object",
      "required": [
        "bank_id",
        "branch_number",
        "holder_name"
      ],
      "properties": {
        "bank_id": {
          "type": "string"
        },
        "branch_number": {
          "type": "string"
        },
        "holder_name": {
          "type": "string"
        },
        "reference": {
          "type": "string"
        }
      }
    },
    "error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "loginRequest": {
      "type": "object",
      "required": [
        "username_or_email",
        "password"
      ],
      "properties": {
        "password": {
          "type": "string",
          "minLength": 1
        },
        "username_or_email": {
          "type": "string",
          "minLength": 1
        }
      }
    },
    "loginResponse": {
      "type": "object",
      "required": [
        "token",
        "expire_date"
      ],
      "properties": {
        "expire_date": {
          "type": "string",
          "format": "date-time"
        },
        "token": {
          "type": "string",
          "minLength": 1
        }
      }
    },
    "principle": {
      "type": "object",
      "required": [
        "id",
        "email",
        "username"
      ],
      "properties": {
        "email": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "username": {
          "type": "string"
        }
      }
    }
  },
  "securityDefinitions": {
    "Bearer": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    }
  }
}`))
}
