// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import (
	models "github.com/ehabterra/flash_api/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// Bank is an autogenerated mock type for the Bank type
type Bank struct {
	mock.Mock
}

// Connect provides a mock function with given fields: account
func (_m *Bank) Connect(account *models.Account) error {
	ret := _m.Called(account)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Account) error); ok {
		r0 = rf(account)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Upload provides a mock function with given fields: number, amount
func (_m *Bank) Upload(number string, amount int64) error {
	ret := _m.Called(number, amount)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, int64) error); ok {
		r0 = rf(number, amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
