// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import (
	models "github.com/ehabterra/flash_api/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// ConnectUserService is an autogenerated mock type for the ConnectUserService type
type ConnectUserService struct {
	mock.Mock
}

// Connect provides a mock function with given fields: account
func (_m *ConnectUserService) Connect(account *models.Account) error {
	ret := _m.Called(account)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Account) error); ok {
		r0 = rf(account)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
