// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// GetBalanceUserService is an autogenerated mock type for the GetBalanceUserService type
type GetBalanceUserService struct {
	mock.Mock
}

// GetUserBalance provides a mock function with given fields: id
func (_m *GetBalanceUserService) GetUserBalance(id string) (float64, error) {
	ret := _m.Called(id)

	var r0 float64
	if rf, ok := ret.Get(0).(func(string) float64); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(float64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
