// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// GetRatesUserService is an autogenerated mock type for the GetRatesUserService type
type GetRatesUserService struct {
	mock.Mock
}

// GetRates provides a mock function with given fields: base, target
func (_m *GetRatesUserService) GetRates(base string, target string) (float64, error) {
	ret := _m.Called(base, target)

	var r0 float64
	if rf, ok := ret.Get(0).(func(string, string) float64); ok {
		r0 = rf(base, target)
	} else {
		r0 = ret.Get(0).(float64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(base, target)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
