// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import (
	models "github.com/ehabterra/flash_api/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// LoginUserService is an autogenerated mock type for the LoginUserService type
type LoginUserService struct {
	mock.Mock
}

// GetUserByUsernameOrEmail provides a mock function with given fields: usernameOrEmail
func (_m *LoginUserService) GetUserByUsernameOrEmail(usernameOrEmail string) (*models.User, error) {
	ret := _m.Called(usernameOrEmail)

	var r0 *models.User
	if rf, ok := ret.Get(0).(func(string) *models.User); ok {
		r0 = rf(usernameOrEmail)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(usernameOrEmail)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
