// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// SendUserService is an autogenerated mock type for the SendUserService type
type SendUserService struct {
	mock.Mock
}

// Send provides a mock function with given fields: id, usernameOrEmail, amount
func (_m *SendUserService) Send(id string, usernameOrEmail string, amount int64) error {
	ret := _m.Called(id, usernameOrEmail, amount)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, int64) error); ok {
		r0 = rf(id, usernameOrEmail, amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
