// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewSendParams creates a new SendParams object
//
// There are no default values defined in the spec.
func NewSendParams() SendParams {

	return SendParams{}
}

// SendParams contains all the bound params for the send operation
// typically these are obtained from a http.Request
//
// swagger:parameters Send
type SendParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  In: body
	*/
	Amount int64
	/*
	  Required: true
	  In: path
	*/
	UsernameOrEmail string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewSendParams() beforehand.
func (o *SendParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body int64
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("amount", "body", "", err))
		} else {
			// no validation required on inline body
			o.Amount = body
		}
	}

	rUsernameOrEmail, rhkUsernameOrEmail, _ := route.Params.GetOK("username_or_email")
	if err := o.bindUsernameOrEmail(rUsernameOrEmail, rhkUsernameOrEmail, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindUsernameOrEmail binds and validates parameter UsernameOrEmail from path.
func (o *SendParams) bindUsernameOrEmail(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.UsernameOrEmail = raw

	return nil
}
