// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewUploadParams creates a new UploadParams object
//
// There are no default values defined in the spec.
func NewUploadParams() UploadParams {

	return UploadParams{}
}

// UploadParams contains all the bound params for the upload operation
// typically these are obtained from a http.Request
//
// swagger:parameters Upload
type UploadParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: path
	*/
	AccountNumber string
	/*
	  In: body
	*/
	Amount int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewUploadParams() beforehand.
func (o *UploadParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rAccountNumber, rhkAccountNumber, _ := route.Params.GetOK("account_number")
	if err := o.bindAccountNumber(rAccountNumber, rhkAccountNumber, route.Formats); err != nil {
		res = append(res, err)
	}

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body int64
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("amount", "body", "", err))
		} else {
			// no validation required on inline body
			o.Amount = body
		}
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindAccountNumber binds and validates parameter AccountNumber from path.
func (o *UploadParams) bindAccountNumber(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.AccountNumber = raw

	return nil
}
